# Site settings
title: SmallzooDev Wiki 
url: "https://SmallzooDev.github.io"
baseurl: ""
description: >
    SmallzooDev 블로그

# My information
email: smallzooDev@gmail.com
author: SmallzooDev 
profile: 개발 잘하고 싶은 사람 
twitter_username: smallzoodev 
github_username: SmallzooDev
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: SmallzooDev/SmallzooDev.github.io
  repo_id: SAMPLE-VALUE
  category: Announcements
  category_id: SAMPLE-VALUE

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/SmallzooDev/johngrib.github.io/blame/master/_wiki"
edit: "https://github.com/SmallzooDev/johngrib.github.io/edit/master/_wiki"
issue: "https://github.com/SmallzooDev/johngrib.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
